/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapsis_online;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Aal
 */
public class input_jadwal extends javax.swing.JInternalFrame {

    /**
     * Creates new form input_jadwal
     */
    public input_jadwal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmb_hari = new javax.swing.JComboBox<>();
        cmb_jam = new javax.swing.JComboBox<>();
        txt_kdmatpel = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        txt_nmmatpel = new javax.swing.JTextField();
        txt_kdguru = new javax.swing.JTextField();
        btn_cariguru = new javax.swing.JButton();
        txt_nmguru = new javax.swing.JTextField();
        txt_kodekelas = new javax.swing.JTextField();
        btn_carikelas = new javax.swing.JButton();
        btn_simapn = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Hari");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Jam");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("kode Matpel");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Nama Matpel");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("kode Guru");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Nama Guru");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Kelas");

        cmb_hari.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmb_hari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));

        cmb_jam.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmb_jam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07.00-08.00", "08.00-09.00", "10.00-11.00", "11.00-12.00" }));

        txt_kdmatpel.setEditable(false);

        btn_cari.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        txt_nmmatpel.setEditable(false);

        txt_kdguru.setEditable(false);

        btn_cariguru.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_cariguru.setText("Cari");
        btn_cariguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariguruActionPerformed(evt);
            }
        });

        txt_nmguru.setEditable(false);

        txt_kodekelas.setEditable(false);

        btn_carikelas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_carikelas.setText("Cari");
        btn_carikelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carikelasActionPerformed(evt);
            }
        });

        btn_simapn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_simapn.setText("Simpan");
        btn_simapn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simapnActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_update.setText("Update");

        btn_hapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_hapus.setText("Hapus");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rapsis_online/alfalah0.jpg"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("JADWAL MATA PELAJARAN ");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("DAN GURU PENGAJAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(59, 59, 59)
                        .addComponent(txt_kodekelas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_jam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kdmatpel)
                            .addComponent(txt_nmmatpel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nmguru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kdguru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_carikelas)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_simapn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cariguru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel10)))
                .addGap(0, 54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmb_hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_jam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_kdmatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btn_cari)
                            .addComponent(btn_simapn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nmmatpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btn_update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kdguru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btn_cariguru)
                    .addComponent(btn_hapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_nmguru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_kodekelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_carikelas))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                popup_matpel dialog = new popup_matpel(new javax.swing.JFrame(),true);
                dialog.setVisible(true);
                if(dialog.getData().toString().equals("")){
                }else{
                    txt_kdmatpel.setText(dialog.getData()[0]);
                    txt_nmmatpel.setText(dialog.getData()[1]);
 
                }
            }
        });
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_cariguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariguruActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                popup_guru dialog = new popup_guru(new javax.swing.JFrame(),true);
                dialog.setVisible(true);
                if(dialog.getData()[0].toString().equals("")){
                    
                }else{
                    txt_kdguru.setText(dialog.getData()[0]);
                    txt_nmguru.setText(dialog.getData()[2]);
 
                }
            }
        });
    }//GEN-LAST:event_btn_cariguruActionPerformed

    private void btn_carikelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carikelasActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                popup_kelas dialog = new popup_kelas(new javax.swing.JFrame(),true);
                dialog.setVisible(true);
                if(dialog.getData().toString().equals("")){
                }else{
                    txt_kodekelas.setText(dialog.getData()[0]);
                    
 
                }
            }
        });
    }//GEN-LAST:event_btn_carikelasActionPerformed

    private void btn_simapnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simapnActionPerformed
        // TODO add your handling code here:
        String hari = "";
        String jam = "";
        if(cmb_hari.getSelectedIndex()== 1){
            hari ="Senin";
        }else if(cmb_hari.getSelectedIndex()==2){
            hari = "Selasa";
        }else if(cmb_hari.getSelectedIndex()==3){
            hari = "Rabu";
        }else if(cmb_hari.getSelectedIndex()==4){
            hari = "Kamis";
        }else if(cmb_hari.getSelectedIndex()==6){
            hari = "Jumat";
        }else if(cmb_hari.getSelectedIndex()==7){
            hari = "Sabtu";
        }
        if(cmb_jam.getSelectedIndex()==0){
            jam = "07.00-08.00";
        }else if(cmb_jam.getSelectedIndex()==1){
            jam = "08.00-09.00";
        }else if(cmb_jam.getSelectedIndex()==2){
            jam = "10.00-11.00";
        }else if(cmb_jam.getSelectedIndex()==3){
            jam = "11.00-12.00";
        }
        try{
            java.sql.Connection conn = (java.sql.Connection)rapsis_online.koneksi.konekDb();
            String sql1 = "insert into tbl_jadwal (hari,jam,kd_matpel,nm_matpel,kd_guru,nm_guru,kd_kelas)values('"+hari+"',"
                                     + "'"+jam+"',"
                                    + "'"+txt_kdmatpel.getText()+"',"
                                    + "'"+txt_nmmatpel.getText()+"',"
                                    + "'"+txt_kdguru.getText()+"',"
                                    + "'"+txt_nmguru.getText()+"',"
                                    + "'"+txt_kodekelas.getText()+"')";
                            java.sql.PreparedStatement pst = conn.prepareStatement(sql1);
                pst.execute();
                hapus();
                JOptionPane.showMessageDialog(null, "Data berhasil Disimpan");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_simapnActionPerformed

public void hapus(){
    cmb_hari.setSelectedIndex(0);
    cmb_jam.setSelectedIndex(0);
    txt_kdmatpel.setText("");
    txt_nmmatpel.setText("");
    txt_kdguru.setText("");
    txt_nmguru.setText("");
    txt_kodekelas.setText("");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_cariguru;
    private javax.swing.JButton btn_carikelas;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simapn;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_hari;
    private javax.swing.JComboBox<String> cmb_jam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_kdguru;
    private javax.swing.JTextField txt_kdmatpel;
    private javax.swing.JTextField txt_kodekelas;
    private javax.swing.JTextField txt_nmguru;
    private javax.swing.JTextField txt_nmmatpel;
    // End of variables declaration//GEN-END:variables
}
