/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapsis_online;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Aal
 */
public class input_guru extends javax.swing.JInternalFrame {
 String [] kolom = new String[11];
String [] isi = new String[11];
public String [] dataPopup = {"","","","","","","","",""};
    /**
     * Creates new form input_guru
     */
    public input_guru() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_nip = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_tempat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_tanggal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rb_pria = new javax.swing.JRadioButton();
        rb_wanita = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmb_pendidikan = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmb_jurusan = new javax.swing.JComboBox<>();
        btn_cari = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("INPUT GURU");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Kode Guru");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("NIP");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Nama");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Tempat Lahir");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Tanggal Lahir");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Jenis Kelamin");

        rb_pria.setBackground(new java.awt.Color(0, 102, 0));
        buttonGroup1.add(rb_pria);
        rb_pria.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rb_pria.setForeground(new java.awt.Color(240, 240, 240));
        rb_pria.setText("Pria");

        rb_wanita.setBackground(new java.awt.Color(0, 102, 0));
        buttonGroup1.add(rb_wanita);
        rb_wanita.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rb_wanita.setForeground(new java.awt.Color(240, 240, 240));
        rb_wanita.setText("Wanita");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Alamat");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Pendidikan");

        cmb_pendidikan.setBackground(new java.awt.Color(204, 204, 0));
        cmb_pendidikan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmb_pendidikan.setForeground(new java.awt.Color(240, 240, 240));
        cmb_pendidikan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "SMA", "D3", "S1", "S2", "S3" }));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Jurusan");

        cmb_jurusan.setBackground(new java.awt.Color(204, 204, 0));
        cmb_jurusan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cmb_jurusan.setForeground(new java.awt.Color(240, 240, 240));
        cmb_jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Ekonomi", "Akutansi", "Pendidikan", "Agama", "Teknik Informatika", "Manajemen", "Hukum" }));

        btn_cari.setBackground(new java.awt.Color(204, 204, 0));
        btn_cari.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        btn_simpan.setBackground(new java.awt.Color(204, 204, 0));
        btn_simpan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(204, 204, 0));
        btn_update.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(204, 204, 0));
        btn_hapus.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rapsis_online/alfalah0.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_nip, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_simpan))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_tempat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_pendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(rb_pria)
                                .addGap(18, 18, 18)
                                .addComponent(rb_wanita))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_simpan)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_update)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_tempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_pria)
                        .addComponent(rb_wanita)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmb_pendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(cmb_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
         String jenkel ="";
         String pendidikan ="";
         String jurusan = "";
        if(rb_pria.isSelected()){
            jenkel ="Pria";
        }else if(rb_wanita.isSelected()){
            jenkel = "Wanita";
        }else{
            jenkel = "";
        }
        if(cmb_pendidikan.getSelectedIndex()== 0){
            pendidikan ="";
        }else if(cmb_pendidikan.getSelectedIndex()== 1){
            pendidikan ="SMA";
        }else if (cmb_pendidikan.getSelectedIndex()== 2){
            pendidikan ="D3";
        } else if (cmb_pendidikan.getSelectedIndex()== 3){
            pendidikan = "S1";
        }else if(cmb_pendidikan.getSelectedIndex()== 4){
            pendidikan = "S2";
        }else if(cmb_pendidikan.getSelectedIndex()== 5){
            pendidikan = "S3";
        }
        
        if(cmb_jurusan.getSelectedIndex()== 0){
            jurusan ="";
        }else if(cmb_jurusan.getSelectedIndex() == 1){
            jurusan ="Ekonomi";
        }else if(cmb_jurusan.getSelectedIndex() == 2){
            jurusan = "Akutansi";
        }else if(cmb_jurusan.getSelectedIndex() == 3){
            jurusan = "Pendidikan";
        }else if(cmb_jurusan.getSelectedIndex() == 4){
            jurusan = "Agama";
        }else if(cmb_jurusan.getSelectedIndex() == 5){
            jurusan = "Teknik Informatika";
        }else if(cmb_jurusan.getSelectedIndex() == 6){
            jurusan = "Manajemen";
        }else if(cmb_jurusan.getSelectedIndex() == 7){
            jurusan = "Hukum";
        }
        if(txt_kode.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kode Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            txt_kode.requestFocus();
        }else if(txt_nama.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nama  Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            txt_nama.requestFocus();
        }else if(txt_tempat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Tempat Lahir Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            txt_tempat.requestFocus();
        }else if(txt_tanggal.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Tanggal Lahir Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            txt_tanggal.requestFocus();
        }else if(jenkel.equals("")){
            JOptionPane.showMessageDialog(null, "Jenis kelamin Belum Dipilih Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            rb_pria.requestFocus();
        }else if(txt_alamat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Alamat Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            txt_alamat.requestFocus();
        }else if(cmb_pendidikan.equals("")){
            JOptionPane.showMessageDialog(null, "Pendidikan Belum dipilih", "Perhatian",JOptionPane.WARNING_MESSAGE);
            cmb_pendidikan.requestFocus();
        }else if(cmb_jurusan.equals("")){
            JOptionPane.showMessageDialog(null, "jurusan Belum dipilih", "Perhatian",JOptionPane.WARNING_MESSAGE);
            cmb_jurusan.requestFocus();
        }else if(txt_nip.getText().equals("")){
            JOptionPane.showMessageDialog(null, "NIP Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            txt_nip.requestFocus();
        }
        else{
            try{
                java.sql.Connection conn = (java.sql.Connection)rapsis_online.koneksi.konekDb();
                String sql = "select kd_guru from tbl_data_guru where kd_guru ='"+txt_kode.getText()+"'";
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet rs = stm.executeQuery(sql);
                if(rs.next()){
                    if(txt_kode.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "Kode Guru Sudah Ada", "Error", JOptionPane.PLAIN_MESSAGE);
                    }
                }else{
                    Object [] options = {"Simpan","Lihat Kembali"};
                    int n = JOptionPane.showOptionDialog(null,
                            "<html>Yakin<b><i>"+txt_kode.getText()+" "+"</i></b>akan disimpan?</html>", 
                            "Konfirmasi",JOptionPane.YES_NO_OPTION, 
                            JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
                    if(n == javax.swing.JOptionPane.YES_OPTION){
                        try{
                            java.sql.Connection con = (java.sql.Connection)rapsis_online.koneksi.konekDb();
                            String sql1 = "insert into tbl_data_guru values('"+txt_kode.getText()+"',"
                                     + "'"+txt_nip.getText()+"',"
                                    + "'"+txt_nama.getText()+"',"
                                    + "'"+txt_tempat.getText()+"',"
                                    + "'"+txt_tanggal.getText()+"',"
                                    + "'"+jenkel+"',"
                                    + "'"+txt_alamat.getText()+"',"
                                    + "'"+pendidikan+"',"
                                    + "'"+jurusan+"')";
                            java.sql.PreparedStatement pst = conn.prepareStatement(sql1);
                pst.execute();
                hapus();
                JOptionPane.showMessageDialog(null, "Data berhasil Disimpan");
                        }catch(SQLException e){
                            JOptionPane.showMessageDialog(null, e);
                        }
                    }
                }
            }catch(Exception e){
                 System.err.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                popup_guru dialog = new popup_guru(new javax.swing.JFrame(),true);
                dialog.setVisible(true);
                if(dialog.getData()[0].toString().equals("")){
                    
                }else{
                    txt_kode.setText(dialog.getData()[0]);
                    txt_nip.setText(dialog.getData()[1]);
                    txt_nama.setText(dialog.getData()[2]);
                    txt_tempat.setText(dialog.getData()[3]);
                    txt_tanggal.setText(dialog.getData()[4]);
                    if(dialog.getData()[5].equals("Pria")){
                        rb_pria.setSelected(true);
                    }else{
                        rb_wanita.setSelected(true);
                    }
                    txt_alamat.setText(dialog.getData()[6]);
                    if(dialog.getData()[7].equals("SMA")){
                        cmb_pendidikan.setSelectedIndex(1);
                    }else if(dialog.getData()[7].equals("D3")){
                        cmb_pendidikan.setSelectedIndex(2);
                    }else if(dialog.getData()[7].equals("S1")){
                        cmb_pendidikan.setSelectedIndex(3);
                    }else if(dialog.getData()[7].equals("S2")){
                        cmb_pendidikan.setSelectedIndex(4);
                    }else if(dialog.getData()[7].equals("S3")){
                        cmb_pendidikan.setSelectedIndex(5);
                    }else{
                        cmb_pendidikan.setSelectedIndex(0);
                    }
                    if(dialog.getData()[8].equals("Ekonomi")){
                        cmb_jurusan.setSelectedIndex(1);
                    }else if(dialog.getData()[8].equals("Akutansi")){
                        cmb_jurusan.setSelectedIndex(2);
                    }else if(dialog.getData()[8].equals("Pendidikan")){
                        cmb_jurusan.setSelectedIndex(3);
                    }else if(dialog.getData()[8].equals("Agama")){
                        cmb_jurusan.setSelectedIndex(4);
                    }else if(dialog.getData()[8].equals("Teknik Informatika")){
                        cmb_jurusan.setSelectedIndex(5);
                    }else if(dialog.getData()[8].equals("Manajemen")){
                        cmb_jurusan.setSelectedIndex(6);
                    }else if(dialog.getData()[8].equals("Hukum")){
                        cmb_jurusan.setSelectedIndex(7);
                    }else{
                        cmb_jurusan.setSelectedIndex(0);
                    }
                    
                    
                    btn_simpan.setEnabled(false);
                    btn_update.setEnabled(true);
                    btn_hapus.setEnabled(true);
 
                }
            }
        });
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        String pendidikan="";
        String jenkel ="";
        String jurusan ="";
        if(rb_pria.isSelected()){
            jenkel ="Pria";
        }else if(rb_wanita.isSelected()){
            jenkel ="Wanita";
        }else{
            jenkel ="";
        }
         if(cmb_pendidikan.getSelectedIndex()== 0){
            pendidikan ="";
        }else if(cmb_pendidikan.getSelectedIndex()== 1){
            pendidikan ="SMA";
        }else if (cmb_pendidikan.getSelectedIndex()== 2){
            pendidikan ="D3";
        } else if (cmb_pendidikan.getSelectedIndex()== 3){
            pendidikan = "S1";
        }else if(cmb_pendidikan.getSelectedIndex()== 4){
            pendidikan = "S2";
        }else if(cmb_pendidikan.getSelectedIndex()== 5){
            pendidikan = "S3";
        }
        if(cmb_jurusan.getSelectedIndex()== 0){
            jurusan ="";
        }else if(cmb_jurusan.getSelectedIndex() == 1){
            jurusan ="Ekonomi";
        }else if(cmb_jurusan.getSelectedIndex() == 2){
            jurusan = "Akutansi";
        }else if(cmb_jurusan.getSelectedIndex() == 3){
            jurusan = "Pendidikan";
        }else if(cmb_jurusan.getSelectedIndex() == 4){
            jurusan = "Agama";
        }else if(cmb_jurusan.getSelectedIndex() == 5){
            jurusan = "Teknik Informatika";
        }else if(cmb_jurusan.getSelectedIndex() == 6){
            jurusan = "Manajemen";
        }else if(cmb_jurusan.getSelectedIndex() == 7){
            jurusan = "Hukum";
        }
        try{
            java.sql.Connection conn = (java.sql.Connection)rapsis_online.koneksi.konekDb();
            String sql ="select kd_guru from tbl_data_guru where kd_guru ='"+txt_kode.getText()+"'";
            java.sql.Statement stm = conn.createStatement();
           
            
            Object [] options = {"ubah","Lihat Kembali"};
            int n = JOptionPane.showOptionDialog(null, "<html>Yakin<b><i> "+txt_kode.getText()+" "+"</i><b> Akan Diubah?</html>","Konfirmasi",JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
            if(n == javax.swing.JOptionPane.YES_OPTION){
                java.sql.Connection con =(java.sql.Connection)rapsis_online.koneksi.konekDb();
                String sql1 = "update tbl_data_guru set kd_guru = '"+txt_kode.getText()+"',NIP ='"+txt_nip.getText()+"',"
                        + "nm_guru ='"+txt_nama.getText()+"',"
                        + "tmplahir ='"+txt_tempat.getText()+"',"
                        + "tgllahir ='"+txt_tanggal.getText()+"',"
                        + "jenkel ='"+jenkel+"',"
                        + "alamat ='"+txt_alamat.getText()+"',"
                        + "pendidikan ='"+pendidikan+"',"
                        + "jurusan ='"+jurusan+"'"
                        + "where kd_guru ='"+txt_kode.getText()+"'";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql1);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Telah Diupdate!!!!");
                hapus();
            }
            
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error"+e);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
         Object [] options = {"Delete","Lihat Kembali"};
        int n = JOptionPane.showOptionDialog(null, "<html>Yakin <b><i>"+txt_kode.getText()+""+"</i></b>akan Dihapus?</html>",
                "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if(n == JOptionPane.YES_OPTION){
            try{
                java.sql.Connection conn = (java.sql.Connection)rapsis_online.koneksi.konekDb();
            String sql = "delete from tbl_data_guru where kd_guru ='"+txt_kode.getText()+"'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Terhapus!!!!");
            hapus();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Error"+e);
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed
public void hapus(){
    txt_kode.setText("");
    txt_nip.setText("");
    txt_nama.setText("");
    txt_tempat.setText("");
    txt_tanggal.setText("");
    buttonGroup1.clearSelection();
    txt_alamat.setText("");
    cmb_pendidikan.setSelectedIndex(0);
    cmb_jurusan.setSelectedIndex(0);
    
}
public void setDataPopup(String [] dataPopup){
    this.dataPopup = dataPopup;
}
public String [] getDataPopup(){
    return dataPopup;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_jurusan;
    private javax.swing.JComboBox<String> cmb_pendidikan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb_pria;
    private javax.swing.JRadioButton rb_wanita;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nip;
    private javax.swing.JTextField txt_tanggal;
    private javax.swing.JTextField txt_tempat;
    // End of variables declaration//GEN-END:variables
}
