/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapsis_online;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Aal
 */
public class input_siswa extends javax.swing.JInternalFrame {
    String [] kolom = new String[11];
String [] isi = new String[11];
public String [] dataPopup = {"","","","","","","","","","",""};

public String [] kolom(){
    kolom[0] ="NIS";
    kolom[1] ="nama";
    kolom[2] ="temp_lahir";
    kolom[3] ="tgl_lahir";
    kolom[4] ="jenkel";
    kolom[5] ="alamat";
    kolom[6] ="agama";
    kolom[7] ="nm_ortu";
    kolom[8] ="pekerjaan";
    kolom[9] ="tgl_masuk";
    kolom[10] = "kd_kelas";
    return kolom;
}

    /**
     * Creates new form input_siswa
     */
    public input_siswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_tempat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_lahir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rb_pria = new javax.swing.JRadioButton();
        rb_wanita = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_agama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_ortu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_kerja = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_masuk = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_kelas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("DATA SISWA");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rapsis_online/Gambar/SISWA.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("NIS");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Tempat Lahir");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Tanggal Lahir");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Jenis Kelamin");

        rb_pria.setBackground(new java.awt.Color(0, 102, 0));
        buttonGroup1.add(rb_pria);
        rb_pria.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rb_pria.setForeground(new java.awt.Color(240, 240, 240));
        rb_pria.setText("Pria");

        rb_wanita.setBackground(new java.awt.Color(0, 102, 0));
        buttonGroup1.add(rb_wanita);
        rb_wanita.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rb_wanita.setForeground(new java.awt.Color(240, 240, 240));
        rb_wanita.setText("Wanita");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Alamat");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("Agama");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Orang Tua");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Pekerjaan");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Tanggal Masuk");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("Kelas");

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_simpan.setBackground(new java.awt.Color(204, 204, 0));
        btn_simpan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(204, 204, 0));
        btn_update.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(204, 204, 0));
        btn_delete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_delete.setText("Hapus");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_cancel.setBackground(new java.awt.Color(204, 204, 0));
        btn_cancel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel14))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(rb_pria)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rb_wanita)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txt_agama, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_ortu, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_kerja, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_tempat, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_nis, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_simpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_tempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_update)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rb_pria)
                    .addComponent(rb_wanita)
                    .addComponent(btn_cancel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ortu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
         String jenkel ="";
        if(rb_pria.isSelected()){
            jenkel ="Pria";
        }else if(rb_wanita.isSelected()){
            jenkel = "Wanita";
        }else{
            jenkel = "";
        }
        if(txt_nis.getText().equals("")){
            JOptionPane.showMessageDialog(null, "NIS Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            txt_nis.requestFocus();
        }else if(txt_nama.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nama  Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            txt_nama.requestFocus();
        }else if(txt_tempat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Tempat Lahir Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            txt_tempat.requestFocus();
        }else if(txt_lahir.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Tanggal Lahir Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            txt_lahir.requestFocus();
        }else if(jenkel.equals("")){
            JOptionPane.showMessageDialog(null, "Jenis kelamin Belum Dipilih Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            rb_pria.requestFocus();
        }else if(txt_alamat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Alamat Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            txt_alamat.requestFocus();
        }else if(txt_ortu.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nama Orang Tua Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            txt_ortu.requestFocus();
        }else if(txt_kerja.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Pekerjaan Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            txt_kerja.requestFocus();
        }else if(txt_masuk.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Tanggal masuk Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            txt_masuk.requestFocus();
        }else if(txt_agama.getText().equals("")){
            JOptionPane.showMessageDialog(null, "agama Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            txt_agama.requestFocus();
        }else if(txt_kelas.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kelas Masih Kosong", "Perhatian",JOptionPane.WARNING_MESSAGE);
            txt_agama.requestFocus();
        }
        else{
            try{
                java.sql.Connection conn = (java.sql.Connection)rapsis_online.koneksi.konekDb();
                String sql = "select NIS from tbl_data_siswa where NIS ='"+txt_nis.getText()+"'";
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet rs = stm.executeQuery(sql);
                if(rs.next()){
                    if(txt_nis.getText().equals("")){
                        JOptionPane.showMessageDialog(null, "NIS Sudah Ada", "Error", JOptionPane.PLAIN_MESSAGE);
                    }
                }else{
                    Object [] options = {"Simpan","Lihat Kembali"};
                    int n = JOptionPane.showOptionDialog(null,
                            "<html>Yakin<b><i>"+txt_nis.getText()+" "+"</i></b>akan disimpan?</html>", 
                            "Konfirmasi",JOptionPane.YES_NO_OPTION, 
                            JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
                    if(n == javax.swing.JOptionPane.YES_OPTION){
                        try{
                            java.sql.Connection con = (java.sql.Connection)rapsis_online.koneksi.konekDb();
                            String sql1 = "insert into tbl_data_siswa values('"+txt_nis.getText()+"',"
                                    + "'"+txt_nama.getText()+"',"
                                    + "'"+txt_tempat.getText()+"',"
                                    + "'"+txt_lahir.getText()+"',"
                                    + "'"+jenkel+"',"
                                    + "'"+txt_alamat.getText()+"',"
                                    + "'"+txt_agama.getText()+"',"
                                    + "'"+txt_ortu.getText()+"',"
                                    + "'"+txt_kerja.getText()+"',"
                                    + "'"+txt_masuk.getText()+"',"
                                    + "'"+txt_kelas.getText()+"')";
                            java.sql.PreparedStatement pst = conn.prepareStatement(sql1);
                pst.execute();
                hapus();
                JOptionPane.showMessageDialog(null, "Data berhasil Disimpan");
                        }catch(SQLException e){
                            JOptionPane.showMessageDialog(null, e);
                        }
                    }
                }
            }catch(Exception e){
                 System.err.println(e.getMessage());
            }
        }
        
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                popup_siswa dialog = new popup_siswa(new javax.swing.JFrame(),true);
                dialog.setVisible(true);
                if(dialog.getData()[0].toString().equals("")){
                    
                }else{
                    txt_nis.setText(dialog.getData()[0]);
                    txt_nama.setText(dialog.getData()[1]);
                    txt_tempat.setText(dialog.getData()[2]);
                    txt_lahir.setText(dialog.getData()[3]);
                    if(dialog.getData()[4].equals("Pria")){
                        rb_pria.setSelected(true);
                    }else{
                        rb_wanita.setSelected(true);
                    }
                    txt_alamat.setText(dialog.getData()[5]);
                    txt_agama.setText(dialog.getData()[6]);
                    txt_ortu.setText(dialog.getData()[7]);
                    txt_kerja.setText(dialog.getData()[8]);
                    txt_masuk.setText(dialog.getData()[9]);
                    txt_kelas.setText(dialog.getData()[10]);
                    btn_simpan.setEnabled(true);
                    btn_update.setEnabled(true);
                    btn_delete.setEnabled(true);
                   
                }
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        String jenkel ="";
        if(rb_pria.isSelected()){
            jenkel ="Pria";
        }else if(rb_wanita.isSelected()){
            jenkel ="Wanita";
        }else{
            jenkel ="";
        }
         try{
            java.sql.Connection conn = (java.sql.Connection)rapsis_online.koneksi.konekDb();
            String sql ="select NIS from tbl_data_siswa where NIS ='"+txt_nis.getText()+"'";
            java.sql.Statement stm = conn.createStatement();
           
            
            Object [] options = {"ubah","Lihat Kembali"};
            int n = JOptionPane.showOptionDialog(null, "<html>Yakin<b><i> "+txt_nis.getText()+" "+"</i><b> Akan Diubah?</html>","Konfirmasi",JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,null,options,options[0]);
            if(n == javax.swing.JOptionPane.YES_OPTION){
                java.sql.Connection con =(java.sql.Connection)rapsis_online.koneksi.konekDb();
                String sql1 = "update tbl_data_siswa set NIS = '"+txt_nis.getText()+"',nama ='"+txt_nama.getText()+"',"
                        + "temp_lahir ='"+txt_tempat.getText()+"',"
                        + "tgl_lahir ='"+txt_lahir.getText()+"',"
                        + "jenkel ='"+jenkel+"',"
                        + "alamat ='"+txt_alamat.getText()+"',"
                        + "agama ='"+txt_agama.getText()+"',"
                        + "nm_ortu ='"+txt_ortu.getText()+"',"
                        + "pekerjaan ='"+txt_kerja.getText()+"',"
                        + "tgl_masuk ='"+txt_masuk.getText()+"',"
                        + "kd_kelas ='"+txt_kelas.getText()+"' "
                        + "where NIS ='"+txt_nis.getText()+"'";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql1);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                hapus();
            }
            
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error"+e);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        Object [] options = {"Delete","Lihat Kembali"};
        int n = JOptionPane.showOptionDialog(null, "<html>Yakin <b><i>"+txt_nis.getText()+""+"</i></b>akan Dihapus?</html>",
                "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        if(n == JOptionPane.YES_OPTION){
            try{
                java.sql.Connection conn = (java.sql.Connection)rapsis_online.koneksi.konekDb();
            String sql = "delete from tbl_data_siswa where NIS ='"+txt_nis.getText()+"'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Terhapus");
            hapus();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Error"+e);
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_btn_cancelActionPerformed
public void hapus(){
    txt_nis.setText("");
    txt_nama.setText("");
    txt_tempat.setText("");
    txt_lahir.setText("");
    buttonGroup1.clearSelection();
    txt_alamat.setText("");
    txt_agama.setText("");
    txt_ortu.setText("");
    txt_masuk.setText("");
    txt_kerja.setText("");
    txt_kelas.setText("");
}
public void setDataPopup(String [] dataPopup){
    this.dataPopup = dataPopup;
}
public String [] getDataPopup(){
    return dataPopup;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb_pria;
    private javax.swing.JRadioButton rb_wanita;
    private javax.swing.JTextField txt_agama;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_kelas;
    private javax.swing.JTextField txt_kerja;
    private javax.swing.JTextField txt_lahir;
    private javax.swing.JTextField txt_masuk;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nis;
    private javax.swing.JTextField txt_ortu;
    private javax.swing.JTextField txt_tempat;
    // End of variables declaration//GEN-END:variables
}
