/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapsis_online;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aal
 */
public class popup_siswa extends javax.swing.JDialog {
    String [] data = new String[11];
input_siswa siswa = new input_siswa();
private DefaultTableModel tblModel;
    /**
     * Creates new form popup_siswa
     */
    public popup_siswa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        tblModel = new DefaultTableModel();
        tabel_siswa.setModel(tblModel);
        setDefaultTable();
    }
      public void setDefaultTable(){
         tblModel = new DefaultTableModel();
         tabel_siswa.setModel(tblModel);
         tblModel.addColumn("NIS");
         tblModel.addColumn("nama");
         tblModel.addColumn("Tempat Lahir");
         tblModel.addColumn("Tanggal Lahir");
         tblModel.addColumn("Jenis Kelamin");
         tblModel.addColumn("Alamat");
         tblModel.addColumn("Agama");
         tblModel.addColumn("Nama Orang Tua");
         tblModel.addColumn("Pekerjaan");
         tblModel.addColumn("Tanggal Masuk");
         tblModel.addColumn("Kelas");
         try{
             java.sql.Connection conn = (java.sql.Connection)rapsis_online.koneksi.konekDb();
             java.sql.Statement stm = conn.createStatement();
             java.sql.ResultSet rs = stm.executeQuery("select * from tbl_data_siswa");
             while(rs.next()){
                data [0] = rs.getString(1);
                 data [1] = rs.getString(2);
                 data [2] = rs.getString(3);
                 data [3] = rs.getString(4);
                 data [4] = rs.getString(5);
                 data [5] = rs.getString(6);
                 data [6] = rs.getString(7);
                 data [7] = rs.getString(8);
                 data [8] = rs.getString(9);
                 data [9] = rs.getString(10);
                 data [10] = rs.getString(11);
                 tblModel.addRow(data);
             }
             stm.close();
             rs.close();
         }catch(Exception e){
             System.out.println("Data gagal disimpan"+e.getMessage());
         }
        
     }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb_siswa = new javax.swing.JComboBox<>();
        txt_siswa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_siswa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmb_siswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "NIS", "Nama" }));

        txt_siswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_siswaKeyPressed(evt);
            }
        });

        tabel_siswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Tempat Lahir", "Tanggal Lahir", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        tabel_siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_siswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_siswa);

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("*) Klik Pada Tabel Untuk Memilih Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cmb_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_siswaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_siswaKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()== evt.VK_ENTER){
            hapusTabel();
            String Key;
            if(cmb_siswa.getSelectedItem().toString().equals("NIS")){
                Key ="NIS";
            }else{
                Key ="nama";
            }
            try{
                java.sql.Connection conn = (java.sql.Connection)rapsis_online.koneksi.konekDb();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet rs = stm.executeQuery("select NIS,nama,temp_lahir,tgl_lahir,jenkel,alamat,agama,nm_ortu,pekerjaan,tgl_masuk,kd_kelas from tbl_data_siswa  where "+Key+" like '%"+txt_siswa.getText()+"%'");
                while(rs.next()){
                    data [0] = rs.getString(1);
                    data [1] = rs.getString(2);
                    data [2] = rs.getString(3);
                    data [3] = rs.getString(4);
                    data [4] = rs.getString(5);
                    data [5] = rs.getString(6);
                    data [6] = rs.getString(7);
                    data [7] = rs.getString(8);
                    data [8] = rs.getString(9);
                    data [9] = rs.getString(10);
                    data [10] = rs.getString(11);
                    tblModel.addRow(data);
                    
                }
                rs.close();
                stm.close();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error"+e);
            }
        }
    }//GEN-LAST:event_txt_siswaKeyPressed

    private void tabel_siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_siswaMouseClicked
        // TODO add your handling code here:
        int row = tabel_siswa.getSelectedRow();
        if(evt.getClickCount()== 1){
            siswa.setDataPopup(new String []{
                tblModel.getValueAt(row, 0).toString(),
                tblModel.getValueAt(row, 1).toString(),
                tblModel.getValueAt(row, 2).toString(),
                tblModel.getValueAt(row, 3).toString(),
                tblModel.getValueAt(row, 4).toString(),
                tblModel.getValueAt(row, 5).toString(),
                tblModel.getValueAt(row, 6).toString(),
                tblModel.getValueAt(row, 7).toString(),
                tblModel.getValueAt(row, 8).toString(),
                tblModel.getValueAt(row, 9).toString(),
                tblModel.getValueAt(row, 10).toString()
            });
           
            this.dispose();
        }
    }//GEN-LAST:event_tabel_siswaMouseClicked
public String [] getData(){
    return siswa.getDataPopup();
    
}


public void hapusTabel(){
    int rowCount = tabel_siswa.getRowCount();
    for(int i = 0; i < rowCount;i++){
        tblModel.removeRow(0);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popup_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popup_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popup_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popup_siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                popup_siswa dialog = new popup_siswa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_siswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_siswa;
    private javax.swing.JTextField txt_siswa;
    // End of variables declaration//GEN-END:variables
}
