/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapsis_online;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aal
 */
public class popup_guru extends javax.swing.JDialog {
String [] data = new String[9];
input_guru guru= new input_guru();
private DefaultTableModel tblModel;
    /**
     * Creates new form popup_guru
     */
    public popup_guru(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         this.setLocationRelativeTo(null);
        tblModel = new DefaultTableModel();
        tabel_guru.setModel(tblModel);
        setDefaultTable();
    }
    public void setDefaultTable(){
         tblModel = new DefaultTableModel();
         tabel_guru.setModel(tblModel);
         tblModel.addColumn("Kode Guru");
         tblModel.addColumn("NIP");
         tblModel.addColumn("Nama");
         tblModel.addColumn("Tempat Lahir");
         tblModel.addColumn("Tanggal Lahir");
         tblModel.addColumn("Jenis Kelamin");
         tblModel.addColumn("Alamat");
         tblModel.addColumn("Pendidikan");
         tblModel.addColumn("Jurusan");
         try{
             java.sql.Connection conn = (java.sql.Connection)rapsis_online.koneksi.konekDb();
             java.sql.Statement stm = conn.createStatement();
             java.sql.ResultSet rs = stm.executeQuery("select * from tbl_data_guru");
             while(rs.next()){
                data [0] = rs.getString(1);
                 data [1] = rs.getString(2);
                 data [2] = rs.getString(3);
                 data [3] = rs.getString(4);
                 data [4] = rs.getString(5);
                 data [5] = rs.getString(6);
                 data [6] = rs.getString(7);
                 data [7] = rs.getString(8);
                 data [8] = rs.getString(9);
                 tblModel.addRow(data);
             }
             stm.close();
             rs.close();
         }catch(Exception e){
             System.out.println("Data gagal disimpan"+e.getMessage());
         }
        
     }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb_guru = new javax.swing.JComboBox<>();
        txt_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_guru = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmb_guru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "Kode Guru", "Nama Guru" }));

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cariKeyPressed(evt);
            }
        });

        tabel_guru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_guru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_guruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_guru);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("*) Klik Pada Tabel Untuk Memilih Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmb_guru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 43, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_guru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== evt.VK_ENTER){
            hapusTabel();
            String Key;
            if(cmb_guru.getSelectedItem().toString().equals("Kode Guru")){
                Key ="kd_guru";
            }else{
                Key ="nm_guru";
            }
            try{
                java.sql.Connection conn = (java.sql.Connection)rapsis_online.koneksi.konekDb();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet rs = stm.executeQuery("select kd_guru,nip,nm_guru,tmplahir,tgllahir,jenkel,alamat,pendidikan,jurusan from tbl_data_guru  where "+Key+" like '%"+txt_cari.getText()+"%'");
                while(rs.next()){
                    data [0] = rs.getString(1);
                    data [1] = rs.getString(2);
                    data [2] = rs.getString(3);
                    data [3] = rs.getString(4);
                    data [4] = rs.getString(5);
                    data [5] = rs.getString(6);
                    data [6] = rs.getString(7);
                    data [7] = rs.getString(8);
                    data [8] = rs.getString(9);
                    tblModel.addRow(data);
                    
                }
                rs.close();
                stm.close();
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error"+e);
            }
        }
    }//GEN-LAST:event_txt_cariKeyPressed

    private void tabel_guruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_guruMouseClicked
        // TODO add your handling code here:
         int row = tabel_guru.getSelectedRow();
        if(evt.getClickCount()== 1){
            guru.setDataPopup(new String []{
                tblModel.getValueAt(row, 0).toString(),
                tblModel.getValueAt(row, 1).toString(),
                tblModel.getValueAt(row, 2).toString(),
                tblModel.getValueAt(row, 3).toString(),
                tblModel.getValueAt(row, 4).toString(),
                tblModel.getValueAt(row, 5).toString(),
                tblModel.getValueAt(row, 6).toString(),
                tblModel.getValueAt(row, 7).toString(),
                tblModel.getValueAt(row, 8).toString()
            });
        }
        this.dispose();
    }//GEN-LAST:event_tabel_guruMouseClicked
public String [] getData(){
    return guru.getDataPopup();
    
}
public void hapusTabel(){
    int rowCount = tabel_guru.getRowCount();
    for(int i = 0; i < rowCount;i++){
        tblModel.removeRow(0);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popup_guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popup_guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popup_guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popup_guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                popup_guru dialog = new popup_guru(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_guru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_guru;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables
}
